### PR TITLE
Share 7zip between CLIs

### PR DESCRIPTION
**Pull request by teobugslayer**

### CODE REVIEW

**Comment by teobugslayer** [comment]
Please do not review this PR, it's work in progress

**Comment by teobugslayer** [comment]
run ci

**Comment by teobugslayer** [comment]
run ci

**Comment by teobugslayer** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
:+1:

**Comment by teobugslayer** [comment]
Closing and reopening in another PR

**Pull request merged**
