### PR TITLE
Help for timeout option passed to emulate and remote commands

### PR DESCRIPTION
**Pull request by Fatme**
http://teampulse.telerik.com/view#item/284307

### CODE REVIEW

**Comment by tytodorov** [comment]
:+1:

**Comment by rosen-vladimirov** [comment]
:+1:

**Comment by rosen-vladimirov** [comment]
Do we have teampulse story for this, just to be sure it will be documented.

**Comment by Fatme** [comment]
Yes, we have http://teampulse.telerik.com/view#item/284307

**Pull request merged**
