### PR TITLE
Do not wait for hang request to registry.npmjs.org

### PR DESCRIPTION
**Pull request by rosen-vladimirov**
Requests to registry.npmjs.org may often hang, which blocks CLI's execution. Wait for five seconds and in case there's no result, show warning to the user and consider the version as valid.

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by Mitko-Kerezov** [comment]
👍

**Comment by ageorgieva** [comment]
:+1:

**Pull request merged**
