### PR TITLE
Integrate ScreenBuilder v0.0.9

### PR DESCRIPTION
**Pull request by Mitko-Kerezov**
Implements [297315](http://teampulse.telerik.com/view#item/297315)

### CODE REVIEW

**Comment by teobugslayer** [comment]
Actually, we are integrating SB 0.0.8 but we have renamed it to 0.0.9. :+1:

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by teobugslayer** [comment]
run ci

**Comment by Fatme** [comment]
This version of sb has breaking change. We may consider and implement some logic to handle this. This way the old sb projects created with ab-cli will work with the new version of ab-cli.

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by teobugslayer** [comment]
:+1:

**Comment by Mitko-Kerezov** [comment]
Merging this as we decided to release with this breaking change given that screenbuilder 0.0.10 will make all previous screenbuilder projects backwards compatible

**Pull request merged**
