### PR TITLE
Validate hook arguments before execute

### PR DESCRIPTION
**Pull request by TsvetanMilanov**
Since we can have hooks with arguments which are invalid for the AppBuilder CLI (for example the before-livesync hook of nativescript-angular and watch hook of nativescript-dev-typescript) we need to check if the arguments of the hook are valid before we execute it. We can do the check only for hooks which can be executed in our process.

Merge after https://github.com/telerik/mobile-cli-lib/pull/806
Fixes: http://teampulse.telerik.com/view#item/321923

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
:+1:

**Comment by TsvetanMilanov** [comment]
run ci

**Comment by tytodorov** [comment]
👍

**Comment by TsvetanMilanov** [comment]
Closing this because the common lib sha will bi updated with https://github.com/Icenium/icenium-cli/pull/1570

**Pull request closed without merging**
