### PR TITLE
ScreenBuilder integration

### PR DESCRIPTION
**Pull request by ikoevska**

### CODE REVIEW

**Comment by teobugslayer** [comment]
:+1:

**Comment by ikoevska** [comment]
@rosen-vladimirov - I added the configure proxy usage changes in here as I don't want to do a whole bunch of rebasing.

**Comment by rosen-vladimirov** [comment]
:+1:  and :+1:  for the proxy part

**Comment by ikoevska** [comment]
@Fatme & @endarova Please, take a look at the SB part.

**Comment by Fatme** [comment]
:+1:

**Comment by teobugslayer** [comment]
:+1: for --unsafe-perm as well

**Pull request merged**
