### PR TITLE
Improve fetched plugins operations

### PR DESCRIPTION
**Pull request by TsvetanMilanov**
Display fetched plugins.
We should display the fetched plugins in Cordova projects when we list the installed plugins.

Move the prompter in the plugin source and add version parameter when fetching plugin.

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by TsvetanMilanov** [comment]
run ci

**Comment by TsvetanMilanov** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
I've tried to add invalid plugin in Cordova project
```
~/Work/icenium-cli/scratch/appCordovaPlugins $ appbuilder plugin add l1234fasd12e
The plugin 'l1234fasd12e' was not found in our list of verified Cordova plugins. We will try to find it in npm and it will be fetched instead of added.
Searching for plugin in http://registry.npmjs.org..
Searching for plugins in http://npmjs.org...
Searching for plugin in http://registry.npmjs.org..
Searching for plugins with npm search command................................................................................................................................................................................................
Command failed: /bin/sh -c npm install l1234fasd12e --production --ignore-scripts
npm WARN package.json tempPackage@1.0.0 No description
npm WARN package.json tempPackage@1.0.0 No repository field.
npm WARN package.json tempPackage@1.0.0 No README data
npm WARN package.json tempPackage@1.0.0 No license field.
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "/usr/local/nvm/versions/node/v4.2.1/bin/node" "/usr/local/nvm/versions/node/v4.2.1/bin/npm" "install" "l1234fasd12e" "--production" "--ignore-scripts"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/l1234fasd12e
npm ERR! 404 
npm ERR! 404 'l1234fasd12e' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'tempPackage'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/pluginInstallation11681-7224-1l3dsio/npm-debug.log
```

**Comment by rosen-vladimirov** [comment]
Is this output expected:
```
~/Work/icenium-cli/scratch/appCordovaPlugins $ appbuilder plugin find lodash
Searching for plugins in http://npmjs.org..
Searching for plugin in http://registry.npmjs.org..
Searching for plugins with npm search command....
```

**Comment by rosen-vladimirov** [comment]
:+1:

**Pull request merged**
