### PR TITLE
Fix typo in node versions

### PR DESCRIPTION
**Pull request by teobugslayer**
See http://teampulse.telerik.com/view#item/304396

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
hm, I couldn't find 0.12.8 version: 
https://nodejs.org/dist/v0.12.8/ returns 404

**Comment by teobugslayer** [comment]
Well, that's the typo part - it has to be 0.12.7

**Comment by rosen-vladimirov** [comment]
sorry, my bad
:+1:

**Comment by endarova** [comment]
:+1:

**Pull request merged**
