### PR TITLE
Fix await in livesync-service-base

### PR DESCRIPTION
**Pull request by TsvetanMilanov**
Fix await in livesync-service-base

Common lib PR: https://github.com/telerik/mobile-cli-lib/pull/874

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by TsvetanMilanov** [comment]
Closing this PR because the common lib sha will be updated with this PR: https://github.com/Icenium/icenium-cli/pull/1627

**Pull request closed without merging**
