### PR TITLE
Use lodash APIs instead of homebrew ones

### PR DESCRIPTION
**Pull request by teobugslayer**

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
There are some failing tests, also this can be seen as error:
appbuilder-cli build version : 2.8.0-PR2113 Error: There are outstanding futures. Construction call stacks: #1 at FileSystem.readJson (C:\Users\bdtest\AppData\Roaming\npm\node_modules\appbuilder\lib\common\file-system.js:145:20) at Configuration.loadConfig (C:\Users\bdtest\AppData\Roaming\npm\node_modules\appbuilder\lib\config.js:53:25) at C:\Users\bdtest\AppData\Roaming\npm\node_modules\appbuilder\lib\config.js:22:48 #2 at FileSystem.readText (C:\Users\bdtest\AppData\Roaming\npm\node_modules\appbuilder\lib\common\file-system.js:135:21) at C:\Users\bdtest\AppData\Roaming\npm\node_modules\appbuilder\lib\common\file-system.js:140:30 at Function.settle (C:\Users\bdtest\AppData\Roaming\npm\node_modules\appbuilder\node_modules\fibers\future.js:220:26) at FiberFuture.Future.wait (C:\Users\bdtest\AppData\Roaming\npm\node_modules\appbuilder\node_modules\fibers\future.js:487:10) at C:\Users\bdtest\AppData\Roaming\npm\node_modules\appbuilder\lib\config.js:22:69 at Function.Future.assertNoFutureLeftBehind (C:\Users\bdtest\AppData\Roaming\npm\node_modules\appbuilder\node_modules\fibers\future.js:145:9) at C:\Users\bdtest\AppData\Roaming\npm\node_modules\appbuilder\lib\fiber-bootstrap.js:9:16

**Comment by Fatme** [comment]
run ci

**Comment by teobugslayer** [comment]
I do not see failing tests?

**Comment by rosen-vladimirov** [comment]
:+1:  after rebase and green build :)

**Comment by teobugslayer** [comment]
rebased

**Pull request merged**
