### PR TITLE
Refactor progress-indicator to append new line

### PR DESCRIPTION
**Pull request by Mitko-Kerezov**
Append new line after project execution regardless of whether it succeeded or failed.

### CODE REVIEW

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by Fatme** [comment]
:+1:

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by Mitko-Kerezov** [comment]
run ci

**Pull request merged**
