### PR TITLE
Print currently livesynced file name

### PR DESCRIPTION
**Pull request by TsvetanMilanov**
When using `appbuilder livesync platform --watch` the name of the file that is synced is not displayed.

### CODE REVIEW

**Comment by TsvetanMilanov** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
:+1:

**Comment by tytodorov** [comment]
https://cloud.githubusercontent.com/assets/5820656/7367659/b895872a-eda9-11e4-98c3-8d28f85439c3.jpg

**Comment by tytodorov** [comment]
Ithumb up

**Pull request merged**
