### PR TITLE
Add --skipUi option

### PR DESCRIPTION
**Pull request by rosen-vladimirov**
Add --skipUi option and if it is passed, do not open file on `appbuilder edit-configuration <smth>`.

### CODE REVIEW

**Comment by ndinev** [comment]
:+1: Needed for testability reasons

**Comment by teobugslayer** [comment]
Either create a help article, or document it with a comment in the code.

**Comment by rosen-vladimirov** [comment]
Do we want help for this? I prefer to keep it internal (comment in the code could be enough).

**Comment by rosen-vladimirov** [comment]
I was thinking about this code. In fact isn't it better to skip the opening in case the console is not interactive (maybe we should handle this is `$opener`). This way we'll not have to add the code for this new option on every single place where we want to skip opening something. Also QAs will not modify their tests at all, they'll just work.

**Comment by teobugslayer** [comment]
In my experience, at least on Windows, running a script does not make the console non-interactive. One has to specifically write code similar to `appbuilder command > nul` to create non-interactive i/o.

**Comment by rosen-vladimirov** [comment]
ok, so let's keep the new option and conisder improving the opener anyway, right?

**Comment by rosen-vladimirov** [comment]
ok, I've documented the option and applied sorting on the two dictionaries (that's why the changes are so much there), but it will be easier for maintain from now on :) 
Ping @teobugslayer

**Comment by teobugslayer** [comment]
:+1:

**Pull request merged**
