### PR TITLE
Apply livesync changes

### PR DESCRIPTION
**Pull request by Fatme**
Fixes http://teampulse.telerik.com/view#item/297546
Should be fixed after this PR https://github.com/telerik/mobile-cli-lib/pull/397

### CODE REVIEW

**Comment by Fatme** [comment]
run ci

**Comment by Fatme** [comment]
run ci

**Comment by Fatme** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
:+1:

**Comment by rosen-vladimirov** [comment]
run ci

**Pull request merged**
