### PR TITLE
Store user data & login cookie per-environment

### PR DESCRIPTION
**Pull request by teobugslayer**
See http://teampulse.telerik.com/view#item/283384

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
:+1:  but this will require each customer to log on once as we'll change the cookie

**Comment by teobugslayer** [comment]
@rosen-vladimirov - yes, this is described in the TP item.

**Comment by teobugslayer** [comment]
This change will be visible to the users. Once they update appbuilder, the old files won't be found and they'll need to log in once. @ikoevska, should we document this?

**Comment by rosen-vladimirov** [comment]
ah, sorry. 
Great work btw :) We'll all love this feature!!!

**Pull request merged**
