### PR TITLE
Support Nodejs 0.12

### PR DESCRIPTION
**Pull request by rosen-vladimirov**
Change version to 2.8.2
Use ios-sim-portable 1.0.4 and ref-struct from telerik fork.

http://teampulse.telerik.com/view#item/285800

### CODE REVIEW

**Comment by teobugslayer** [comment]
This must be amended and committed after we publish ios-sim-portbale

**Comment by ndinev** [comment]
:+1:

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by Fatme** [comment]
:+1:

**Pull request merged**
