### PR TITLE
Add authentication command

### PR DESCRIPTION
**Pull request by Fatme**
Add-signin and add-signup commands were removed in new version of sb and authentication command was introduced.
Fixes http://teampulse.telerik.com/view#item/292900

### CODE REVIEW

**Comment by teobugslayer** [comment]
I think you need to also delete **add-signup.md**

**Comment by ikoevska** [comment]
Would you, please, update the TeamPulse item for the SB update as well? Right now it says that only add-about is a new command.

**Comment by teobugslayer** [comment]
:+1:

**Comment by Fatme** [comment]
I've updated the teampulse item.

**Pull request merged**
