### PR TITLE
Use genymotion

### PR DESCRIPTION
**Pull request by rosen-vladimirov**
Update package.json to use telerik fork of winreg module (currently it points to vladimirov/specify-registry-version branch). Update common lib.

http://teampulse.telerik.com/view#item/274611

### CODE REVIEW

**Comment by teobugslayer** [comment]
You are missing documentation in the help.txt. Please write a rough draft for @ikoevska

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
ping @ikoevska for help.txt changes

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by teobugslayer** [comment]
:+1:

**Pull request merged**
